# config/database.yml

# This is the standard configuration for Rails apps.
# It uses SQLite for local development and testing.
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# This production section is configured for hosting services like Render or Heroku.
production:
  # It uses the postgresql adapter.
  adapter: postgresql
  encoding: unicode
  pool: 5
  # It reads the connection details from the DATABASE_URL environment variable,
  # which Render will provide to your app automatically.
  url: <%= ENV['DATABASE_URL'] %>